### ISSUE TITLE
Public cannot view meeting documents

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-module-onboard#13]
When logged in to the drupal site, documents show up without any problem. 

However, when not logged in, nothing shows up. For example:

https://bloomington.in.gov/boards/plan/meetings/2017

Looks like:

<img width="1334" alt="screen shot 2017-12-11 at 12 07 40 pm" src="https://user-images.githubusercontent.com/2225624/33843631-eb952044-de6b-11e7-9a2c-492a1798d99f.png">

Maybe this has something to do with the recent release?

**Comment by inghamn** [comment]
There was a deadlock during cache rebuild which, I think, left this page in an empty state.  Since then, the cache has been rebuilt successfully.  The page is working now.
