### ISSUE TITLE
Custom layout needed for council members

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-module-onboard#15]
Currently, council members are shown using the same layout as other board and commission members, however, the information is not as relevant in this context. Rendering council members should use a separate template where each member is shown as: 

Name
Office(s)
Seat Name (== district in this case)
Term Expires

Other boards and commissions should have the Offices field added after the member's name.

**Comment by inghamn** [comment]
Moved to the COB Drupal Theme
https://github.com/City-of-Bloomington/drupal-theme-cob/issues/118
