### ISSUE TITLE
Meeting list should list agendas and packets in separate column from minutes

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-module-onboard#17]
Currently we show all associated files for a meeting in a single column.  For example:

https://bloomington.in.gov/council/meetings/2017

It would make sense to separate agendas and packets from minutes. Agendas and packets are materials that are useful for upcoming meetings, whereas minutes document what actually happened at a meeting. 

In the case of the City Council it may be useful to have a separate column for related legislation, as described in #16.

**Comment by inghamn** [comment]
We switched to listing them all in a single column becuase there wasn't room on screen for four columns of filenames.
![screen](https://user-images.githubusercontent.com/630282/38043216-7ba2b1ee-3284-11e8-905e-c38c2bad7f7a.png)

**Comment by inghamn** [comment]
The council has expressed some concern about the display as well.  The files are all jumbled together.   At some point we need to come up with a good way to display these files.

**Comment by rbdietz** [comment]
Comma separation of files isn't working right on this page... https://bloomington.in.gov/council/meetings/2017

You might consider adding a filetype icon just before the filename.
You might consider a hard return after each file listed.

**Comment by adabutch** [comment]
**note:** This issue should be fixed up when [180](https://github.com/City-of-Bloomington/drupal-theme-cob/pull/180) is merged & pushed to production.

**Comment by inghamn** [comment]
This was handled in the COB Theme.  There is some rudimentary markup in this OnBoard module, but the real display customizations should happen in the theme.
