### ISSUE TITLE
"Member since" not displayed for open seating

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-module-onboard#19]
On a [page for board or commission](https://bloomington.in.gov/boards/jack-hopkins), the "Member Since" title heading is shown, but the date is missing.

Appointed By:
Common Council
Member Since:

**Comment by inghamn** [comment]
For boards and committee seats that are open (not termed), we are not displaying when the members started serving.  We must be reading from the Term start date, and not the Member start date.
