### ISSUE TITLE
Link to meeting videos

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-module-onboard#3]
CATS is recording and hosting videos of board meetings.  We should provide a links to the meetings.

We probably want both a link to CATS archive of all meetings for the board, as well as linking to individual meeting videos on the meetings screen.

See: https://github.com/City-of-Bloomington/OnBoard/issues/173

**Comment by rbdietz** [comment]
The only thing we need for website launch is to include the video link for
the board, not the individual meetings for every meeting.  We can do that
later as a separate project.  R





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov
