### ISSUE TITLE
Display meeting title on meeting documents page

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-module-onboard#6]
Meeting document pages should include the title specified on the corresponding google event. An example page that could include these titles is:
https://bloomington.in.gov/boards/digital-underground/meetings

I believe this is already in the works, but I wanted to document the request in an actual issue. 

This has come up in meetings with City content creators as well as via the feedback form:
https://bloomington.in.gov/crm/tickets/view?ticket_id=160109

**Comment by inghamn** [comment]
This is what module currently does
![screen](https://user-images.githubusercontent.com/630282/38043327-d206a608-3284-11e8-8f25-fbd7a11a796c.png)
